const productQuestions = {
  laptop: [
    "Which company are you interested in?",
    "What's your primary use? (e.g., coding, gaming, business)",
    "Do you prefer a touchscreen laptop?",
    "Is battery backup important to you?",
    "Do you require a backlit keyboard?",
    "Do you use heavy software (e.g., AutoCAD, Premiere Pro)?",
    "Do you need a fingerprint sensor or Windows Hello login?",
  ],
  phone: [
    "Are you looking for a phone with fast charging?",
    "Do you play mobile games frequently?",
    "Do you prefer stock Android or custom UI (e.g., MIUI, One UI)?",
    "Are software updates and security patches important to you?",
    "Do you often use the phone for photography or video recording?",
    "Do you need eSIM support or regular SIM?",
  ],
  shoes: [
    "Do you walk long distances daily?",
    "Are you looking for slip-resistant soles?",
    "Do you need orthopedic support?",
    "Are you looking for sustainable or vegan materials?",
    "Do you need high-ankle or low-cut designs?",
    "Is breathability a key factor for you?",
  ],
  clothing: [
    "Are you looking for office/formal attire or casual wear?",
    "Do you prefer loose fit or slim fit?",
    "Are you interested in sustainable or organic fabric?",
    "Do you need machine-washable clothing?",
    "Do you prefer solid colors, patterns, or prints?",
    "What sleeve length do you prefer? (e.g., full, half, sleeveless)",
  ],
  watch: [
    "Do you want a watch with fitness tracking features?",
    "Is water resistance important for you?",
    "Are you looking for smartwatch compatibility with your phone?",
    "Do you want replaceable watch straps?",
    "Do you prefer a round dial or square/rectangular?",
    "Are you interested in a chronograph function?",
  ],
  headphones: [
    "Do you want headphones for professional audio editing?",
    "Is foldable or compact design important to you?",
    "Do you want ambient sound or transparency mode?",
    "Do you prefer touch controls or physical buttons?",
    "Are you sensitive to ear pressure from over-ear designs?",
    "Do you need low-latency mode for gaming?",
  ],
  refrigerator: [
    "Do you need convertible freezer space?",
    "Do you want a water/ice dispenser?",
    "Do you prefer a model with inverter compressor?",
    "Is stabilizer-free operation important to you?",
    "Do you want a refrigerator with smart Wi-Fi features?",
    "Do you cook frequently or store more frozen food?",
  ],
  tv: [
    "Do you need a TV that supports screen mirroring or casting?",
    "Are you planning to wall-mount the TV?",
    "Do you need HDMI ARC or optical audio output?",
    "Are you interested in Dolby Vision or HDR10+ support?",
    "Do you stream from OTT apps like Netflix, Prime, Disney+?",
    "Do you prefer built-in voice assistants like Alexa/Google Assistant?",
  ],
  furniture: [
    "Are you furnishing a home or office space?",
    "Do you prefer foldable or space-saving furniture?",
    "Do you require multi-functional pieces (e.g., sofa-cum-bed)?",
    "Is modular design important for you?",
    "Are you looking for DIY assembly or full installation?",
    "Do you need furniture with warranty or maintenance plans?",
  ],
  makeup: [
    "Are you looking for cruelty-free or vegan products?",
    "Do you prefer liquid, cream, or powder-based products?",
    "Is your skin type oily, dry, or combination?",
    "Are you shopping for daily wear or special occasions?",
    "Do you have any specific brand preferences?",
    "Do you need water-resistant or long-wear formulas?",
  ],
  books: [
    "What genres are you interested in? (e.g., fiction, self-help)",
    "Are you looking for physical books or eBooks?",
    "Do you prefer bestsellers or niche authors?",
    "Do you need books for academic or personal reading?",
    "Do you follow any specific book series or authors?",
    "What language do you prefer to read in?",
  ],
  toys: [
    "What age group is the toy for?",
    "Are you looking for educational toys or just fun?",
    "Do you prefer battery-operated or manual toys?",
    "Is the toy for indoor or outdoor use?",
    "Are you interested in eco-friendly or plastic-free options?",
    "Do you want toys with STEM learning value?",
  ],
  beauty_products: [
    "Is your skin oily, dry, or sensitive?",
    "Are you looking for fragrance-free products?",
    "Do you need SPF in your skincare?",
    "Do you prefer organic or chemical-based products?",
    "Are you targeting issues like acne, aging, or pigmentation?",
    "Do you need travel-size options?",
  ],
};

export default productQuestions; 